# Generated by Django 5.2.8 on 2025-12-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_about_alter_blog_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
